apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: app-project
spec:
  selector:
    app: app-project
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31200
